# Generated by Django 5.1.4 on 2024-12-18 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='readinglist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'list_type'), name='unique_default_list_type'),
        ),
    ]
