# Generated by Django 5.1.4 on 2024-12-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_readinglist_unique_default_list_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readinglist',
            unique_together=set(),
        ),
    ]
