# Generated by Django 5.1.4 on 2024-12-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorTransliteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transliterated_name', models.TextField(help_text="Romanized version of the author's name", verbose_name='Romanized Name')),
                ('type', models.CharField(choices=[('CANONICAL', 'Canonical Name'), ('LEGAL', 'Legal Name')], default='CANONICAL', help_text='Type of name being transliterated', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transliteration', null=True, verbose_name='Notes')),
                ('author', models.ForeignKey(help_text='The author this transliteration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transliterations', to='authors.author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Author Transliteration',
                'verbose_name_plural': 'Author Transliterations',
                'ordering': ['transliterated_name'],
                'unique_together': {('author', 'type')},
            },
        ),
    ]
