# Generated by Django 5.1.4 on 2024-12-14 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_annual_views_author_birth_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birthdate_display',
            field=models.CharField(blank=True, editable=False, help_text='Formatted birth date (YYYY-MM-DD or YYYY)', max_length=10),
        ),
        migrations.AddField(
            model_name='author',
            name='deathdate_display',
            field=models.CharField(blank=True, editable=False, help_text='Formatted death date (YYYY-MM-DD or YYYY)', max_length=10),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of birth (-3000 to future). Use negative values for BC/BCE', null=True, validators=[django.core.validators.MinValueValidator(-3000), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
