# Generated by Django 5.1.4 on 2024-12-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_remove_authortransliteration_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='notes',
        ),
    ]
