# Generated by Django 5.1.4 on 2024-12-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_birthdate_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the author. Supports markdown', null=True),
        ),
    ]
