# Generated by Django 5.1.4 on 2024-12-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_author_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPseudonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this pseudonym', null=True)),
                ('pseudonym', models.OneToOneField(help_text='The pseudonym author entry', on_delete=django.db.models.deletion.CASCADE, related_name='real_author', to='authors.author', verbose_name='Pseudonym')),
                ('real_name', models.ForeignKey(help_text="The author's real identity", on_delete=django.db.models.deletion.CASCADE, related_name='pseudonyms', to='authors.author', verbose_name='Real Name')),
            ],
            options={
                'verbose_name': 'Author Pseudonym',
                'verbose_name_plural': 'Author Pseudonyms',
                'ordering': ['pseudonym__last_name'],
            },
        ),
    ]
