# Generated by Django 5.1.4 on 2024-12-14 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_author_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birthdate_display',
        ),
        migrations.RemoveField(
            model_name='author',
            name='deathdate_display',
        ),
        migrations.AddField(
            model_name='author',
            name='birthdate',
            field=models.CharField(blank=True, help_text='Date format: YYYY or YYYY-MM or YYYY-MM-DD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='deathdate',
            field=models.CharField(blank=True, help_text='Date format: YYYY or YYYY-MM or YYYY-MM-DD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_day',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_month',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthplace',
            field=models.CharField(blank=True, help_text='Place of birth of the author. Should contain city, state, and country', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='canonical_name',
            field=models.CharField(help_text='Canonical name of the author', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, help_text='Family name used for sorting (derived from canonical name)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Legal name of the author. Should be Family Name, Given Name', max_length=255, null=True),
        ),
    ]
