# Generated by Django 5.1.4 on 2024-12-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_remove_author_birthdate_display_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='author',
            name='canonical_name',
            field=models.CharField(help_text='Canonical name of the author', max_length=255),
        ),
    ]
