# Generated by Django 5.1.4 on 2024-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_rename_image_author_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthplace',
            field=models.TextField(blank=True, help_text='Place of birth of the author. Should contain city, state, and country', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='canonical_name',
            field=models.TextField(help_text='Canonical name of the author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.TextField(blank=True, db_index=True, help_text='Family name used for sorting (derived from canonical name)', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='legal_name',
            field=models.TextField(blank=True, help_text='Legal name of the author. Should be Family Name, Given Name', null=True),
        ),
    ]
