# Generated by Django 5.1.4 on 2024-12-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the publication series')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('isfdb_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ISFDB publication series ID', null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Publication Series',
                'verbose_name_plural': 'Publication Series',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='publication_name_130445_idx')],
            },
        ),
    ]
