# Generated by Django 5.1.4 on 2024-12-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publicationseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationSeriesTransliteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transliterated_text', models.TextField(help_text='Romanized version of the publication series name', verbose_name='Romanized Text')),
                ('publication_series', models.ForeignKey(help_text='The original publication series this transliteration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transliterations', to='publications.publicationseries', verbose_name='Publication Series')),
            ],
            options={
                'verbose_name': 'Publication Series Transliteration',
                'verbose_name_plural': 'Publication Series Transliterations',
                'ordering': ['transliterated_text'],
            },
        ),
    ]
