# Generated by Django 5.1.4 on 2024-12-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publicationseriestransliteration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherTransliteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transliterated_text', models.TextField(help_text='Romanized version of the publisher name', verbose_name='Romanized Text')),
                ('publisher', models.ForeignKey(help_text='The original publisher this transliteration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transliterations', to='publications.publisher', verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Publisher Transliteration',
                'verbose_name_plural': 'Publisher Transliterations',
                'ordering': ['transliterated_text'],
            },
        ),
    ]
