# Generated by Django 5.1.4 on 2024-12-16 17:13

import BookBird.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publishertransliteration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Title of the publication')),
                ('isfdb_tag', models.CharField(blank=True, help_text='ISFDB tag for this publication', max_length=255, null=True)),
                ('publication_date', models.CharField(blank=True, help_text='Publication date in YYYY-MM-DD, YYYY-MM, or YYYY format', max_length=10, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, help_text='Number of pages', null=True)),
                ('format', models.CharField(blank=True, choices=[('HC', 'Hardcover'), ('TP', 'Trade Paperback'), ('AUDIO_CASSETTE', 'Audio Cassette'), ('PB', 'Paperback'), ('QUARTO', 'Quarto'), ('UNKNOWN', 'Unknown'), ('PH', 'Pamphlet'), ('DIGEST', 'Digest'), ('EBOOK', 'Ebook'), ('DOS', 'Dos'), ('PULP', 'Pulp'), ('DIGITAL_AUDIO_DOWNLOAD', 'Digital Audio Download'), ('AUDIO_MP3_CD', 'Audio MP3 CD'), ('OTHER', 'Other'), ('BEDSHEET', 'Bedsheet'), ('OCTAVO', 'Octavo'), ('AUDIO_CD', 'Audio CD'), ('WEBZINE', 'Webzine'), ('A5', 'A5'), ('A4', 'A4'), ('AUDIO_LP', 'Audio LP'), ('TABLOID', 'Tabloid'), ('DIGITAL_AUDIO_PLAYER', 'Digital Audio Player')], help_text='Format/binding type of the publication', max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, help_text='ISBN-10 or ISBN-13', max_length=13, null=True)),
                ('price', models.CharField(blank=True, help_text='Main price of the publication', max_length=50, null=True)),
                ('series_number', models.PositiveIntegerField(blank=True, help_text='Position within the publication series', null=True)),
                ('catalog_id', models.CharField(blank=True, help_text='Catalog ID of the publication', max_length=255, null=True)),
                ('isfdb_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ISFDB publication ID', null=True, unique=True)),
                ('publication_series', models.ForeignKey(blank=True, help_text='Publication series this belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publications.publicationseries')),
                ('publisher', models.ForeignKey(help_text='Publisher of this publication', on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='publications.publisher')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['publication_date', 'title'],
                'indexes': [models.Index(fields=['isbn'], name='publication_isbn_3b5554_idx'), models.Index(fields=['publication_date'], name='publication_publica_1eb6f0_idx'), models.Index(fields=['title'], name='publication_title_28acd5_idx'), models.Index(fields=['-series_number'], name='publication_series__0cfe6c_idx')],
            },
            bases=(models.Model, BookBird.mixins.DateComponentsMixin),
        ),
    ]
