# Generated by Django 5.1.4 on 2024-12-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ctype',
            field=models.CharField(blank=True, choices=[('ANTHOLOGY', 'Anthology'), ('CHAPBOOK', 'Chapbook'), ('COLLECTION', 'Collection'), ('MAGAZINE', 'Magazine'), ('NONFICTION', 'Non-Fiction'), ('NOVEL', 'Novel'), ('OMNIBUS', 'Omnibus'), ('FANZINE', 'Fanzine')], db_index=True, help_text='Type of the publication', max_length=32, null=True),
        ),
    ]
