# Generated by Django 5.1.4 on 2024-12-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_alter_publication_pages_alter_publication_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
