# Generated by Django 5.1.4 on 2024-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publication_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.CharField(blank=True, help_text='Publication date in YYYY-MM-DD, YYYY-MM, or YYYY format', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='series_number',
            field=models.CharField(blank=True, help_text='Position within the publication series', max_length=255, null=True),
        ),
    ]
