# Generated by Django 5.1.4 on 2024-12-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_alter_publication_image_url_and_more'),
        ('titles', '0021_title_popularity_score_alter_title_isfdb_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfdb_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ISFDB ID', null=True, unique=True)),
                ('page', models.CharField(blank=True, help_text='Page number where the title appears in the publication', max_length=255, null=True)),
                ('publication', models.ForeignKey(help_text='Publication containing this title', on_delete=django.db.models.deletion.CASCADE, related_name='contained_titles', to='publications.publication')),
                ('title', models.ForeignKey(help_text='Title appearing in this publication', on_delete=django.db.models.deletion.CASCADE, related_name='publication_appearances', to='titles.title')),
            ],
            options={
                'verbose_name': 'Publication Title',
                'verbose_name_plural': 'Publication Titles',
                'ordering': ['publication', 'page'],
                'indexes': [models.Index(fields=['isfdb_id'], name='publication_isfdb_i_150153_idx'), models.Index(fields=['title'], name='publication_title_i_f7362a_idx'), models.Index(fields=['publication'], name='publication_publica_4a0ef7_idx')],
            },
        ),
    ]
