# Generated by Django 5.1.4 on 2024-12-14 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="ISO 639-2 language code (e.g. 'eng', 'bgr')", max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='3 letter ISO 639-2 language code', regex='^[a-z]{2,3}$')])),
                ('name', models.CharField(help_text="Language name in English (e.g. 'English', 'Bulgarian')", max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('native_name', models.CharField(help_text="Language name in its native form (e.g. 'English', 'Български')", max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='languages_l_code_c4eb52_idx'), models.Index(fields=['name'], name='languages_l_name_0109b7_idx')],
            },
        ),
    ]
