# Generated by Django 5.1.4 on 2024-12-14 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text="Language name in English (e.g. 'English', 'Bulgarian')", max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='language',
            name='native_name',
            field=models.CharField(help_text="Language name in its native form (e.g. 'English', 'Български')", max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
