# Generated by Django 5.1.4 on 2024-12-14 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_name_alter_language_native_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text="ISO 639-2 language code (e.g. 'eng', 'bul')", max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='3 letter ISO 639-2 language code', regex='^[a-z]{2,3}$')]),
        ),
    ]
