# Generated by Django 5.1.4 on 2024-12-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the related object')),
                ('note_text', models.TextField(help_text='Note content. Supports markdown')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this note was last updated')),
                ('note_type', models.CharField(blank=True, help_text='Type/category of the note', max_length=50, null=True)),
                ('content_type', models.ForeignKey(help_text='Type of object this note belongs to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_note_content_948980_idx'), models.Index(fields=['note_type'], name='core_note_note_ty_23f892_idx')],
            },
        ),
    ]
