# Generated by Django 5.1.4 on 2024-12-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfdb_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ISFDB ID', null=True, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Short code identifying the award type', max_length=5)),
                ('name', models.TextField(help_text='Full name of the award type')),
                ('short_name', models.TextField(blank=True, help_text='Short/common name of the award', null=True)),
                ('by', models.TextField(blank=True, help_text='Organization giving the award', null=True)),
                ('for_what', models.TextField(blank=True, db_column='for', help_text='What the award is given for', null=True)),
                ('wikipedia_url', models.URLField(blank=True, help_text="URL of award's Wikipedia page", null=True)),
                ('is_poll', models.BooleanField(default=False, help_text='Indicates if this is a poll rather than a juried award')),
                ('is_non_genre', models.BooleanField(default=False, help_text='Indicates if this is not a speculative fiction award')),
            ],
            options={
                'verbose_name': 'Award Type',
                'verbose_name_plural': 'Award Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='awards_awar_code_fa4467_idx'), models.Index(fields=['name'], name='awards_awar_name_c27354_idx'), models.Index(fields=['isfdb_id'], name='awards_awar_isfdb_i_dedbab_idx')],
            },
        ),
    ]
