# Generated by Django 5.1.4 on 2024-12-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardtype',
            name='for_what',
            field=models.TextField(blank=True, help_text='What the award is given for', null=True),
        ),
    ]
