# Generated by Django 5.1.4 on 2024-12-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_awardtype_for_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardtype',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Short code identifying the award type', max_length=5, null=True),
        ),
    ]
