# Generated by Django 5.1.4 on 2024-12-17 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_awardtype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfdb_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ISFDB ID', null=True, unique=True)),
                ('name', models.TextField(help_text='Name of the award category', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, help_text='Display order within award type', null=True)),
                ('type', models.ForeignKey(help_text='Award type this category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='awards.awardtype')),
            ],
            options={
                'verbose_name': 'Award Category',
                'verbose_name_plural': 'Award Categories',
                'ordering': ['type', 'order', 'name'],
                'indexes': [models.Index(fields=['isfdb_id'], name='awards_awar_isfdb_i_be8fa6_idx'), models.Index(fields=['type', 'order'], name='awards_awar_type_id_250fc0_idx')],
            },
        ),
    ]
