# Generated by Django 5.1.4 on 2024-12-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_titleaward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardtype',
            options={'ordering': ['name'], 'verbose_name': 'Main Award', 'verbose_name_plural': 'Main Awards'},
        ),
    ]
