# Generated by Django 5.1.4 on 2024-12-15 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_language_native_name'),
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['title'], 'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
        migrations.AddField(
            model_name='title',
            name='content_indicator',
            field=models.CharField(blank=True, help_text="Content indicator for omnibuses (e.g. '1,2+ss' indicates parts 1, 2 plus short stories)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='first_pub_date',
            field=models.CharField(blank=True, help_text='Date of first publication in the format YYYY-MM-DD, YYYY-MM, or YYYY', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='first_pub_day',
            field=models.IntegerField(blank=True, help_text='First publication day', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='first_pub_month',
            field=models.IntegerField(blank=True, help_text='First publication month', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='first_pub_year',
            field=models.IntegerField(blank=True, help_text='First publication year', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='is_canonical',
            field=models.BooleanField(default=True, help_text='Is this canonical title or a variant title?'),
        ),
        migrations.AddField(
            model_name='title',
            name='is_graphic',
            field=models.BooleanField(default=False, help_text='Indicates if this title is graphic in nature. Note: Cover art and interior art are not considered graphic'),
        ),
        migrations.AddField(
            model_name='title',
            name='is_juvenile',
            field=models.BooleanField(default=False, help_text='Indicates if this title is aimed at the juvenile/young adult audience'),
        ),
        migrations.AddField(
            model_name='title',
            name='is_non_genre',
            field=models.BooleanField(default=False, help_text='Indicates if this title is not speculative fiction'),
        ),
        migrations.AddField(
            model_name='title',
            name='is_novelization',
            field=models.BooleanField(default=False, help_text='Indicates if this title is a novelization from a movie, TV show, etc.'),
        ),
        migrations.AddField(
            model_name='title',
            name='language',
            field=models.ForeignKey(help_text='Primary language of this title', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='languages.language'),
        ),
        migrations.AddField(
            model_name='title',
            name='parent_title',
            field=models.ForeignKey(blank=True, help_text='Parent canonical title. If null, this is a canonical title; if set, this is a variant title', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_titles', to='titles.title'),
        ),
        migrations.AddField(
            model_name='title',
            name='type',
            field=models.CharField(choices=[('ANTHOLOGY', 'Anthology'), ('BACKCOVERART', 'Back Cover Art'), ('COLLECTION', 'Collection'), ('COVERART', 'Cover Art'), ('INTERIORART', 'Interior Art'), ('EDITOR', 'Editor'), ('ESSAY', 'Essay'), ('INTERVIEW', 'Interview'), ('NOVEL', 'Novel'), ('NONFICTION', 'Non-Fiction'), ('OMNIBUS', 'Omnibus'), ('POEM', 'Poem'), ('REVIEW', 'Review'), ('SERIAL', 'Serial'), ('SHORTFICTION', 'Short Fiction'), ('CHAPBOOK', 'Chapbook')], default='NOVEL', help_text='Type of the title (e.g. Novel, Collection, Anthology)', max_length=20),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.TextField(help_text='Title of the work'),
        ),
    ]
