# Generated by Django 5.1.4 on 2024-12-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series_parent_position',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Position within the parent series (e.g. 1, 1.5, 3)', max_digits=5, null=True),
        ),
    ]
