# Generated by Django 5.1.4 on 2024-12-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_alter_series_series_parent_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='isfdb_id',
            field=models.IntegerField(blank=True, help_text='ISFDB ID for this series', null=True),
        ),
    ]
