# Generated by Django 5.1.4 on 2024-12-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0009_series_isfdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='isfdb_id',
            field=models.IntegerField(blank=True, help_text='ISFDB ID for this series', null=True, unique=True),
        ),
    ]
