# Generated by Django 5.1.4 on 2024-12-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0010_alter_series_isfdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of title page views'),
        ),
    ]
