# Generated by Django 5.1.4 on 2024-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0011_title_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='annual_views',
            field=models.PositiveIntegerField(default=0, help_text='Number of views in the last year'),
        ),
    ]
