# Generated by Django 5.1.4 on 2024-12-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0012_title_annual_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='series_position',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Position within the series (e.g. 1, 1.5, 3)', max_digits=5, null=True),
        ),
    ]
