# Generated by Django 5.1.4 on 2024-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0014_alter_title_isfdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='is_canonical',
            field=models.BooleanField(default=True, help_text='Is this canonical title or a variant title?', null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_graphic',
            field=models.BooleanField(default=False, help_text='Indicates if this title is graphic in nature. Note: Cover art and interior art are not considered graphic', null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_juvenile',
            field=models.BooleanField(default=False, help_text='Indicates if this title is aimed at the juvenile/young adult audience', null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_non_genre',
            field=models.BooleanField(default=False, help_text='Indicates if this title is not speculative fiction', null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_novelization',
            field=models.BooleanField(default=False, help_text='Indicates if this title is a novelization from a movie, TV show, etc.', null=True),
        ),
    ]
