# Generated by Django 5.1.4 on 2024-12-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0015_alter_title_is_canonical_alter_title_is_graphic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titletransliteration',
            name='notes',
        ),
    ]
