# Generated by Django 5.1.4 on 2024-12-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0016_remove_titletransliteration_notes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['title'], name='titles_seri_title_503a67_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['series_parent_position'], name='titles_seri_series__9ec425_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['parent'], name='titles_seri_parent__c5b667_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['isfdb_id'], name='titles_seri_isfdb_i_e95114_idx'),
        ),
    ]
