# Generated by Django 5.1.4 on 2024-12-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0017_series_titles_seri_title_503a67_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Series this title belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='titles.series'),
        ),
    ]
