# Generated by Django 5.1.4 on 2024-12-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_author_notes'),
        ('titles', '0018_title_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Canonical author entry'), (2, 'Interviewee author'), (3, 'Reviewee author')], default=1, help_text='Role of the author for this title')),
                ('author', models.ForeignKey(help_text='Author of the title', on_delete=django.db.models.deletion.CASCADE, related_name='title_relationships', to='authors.author')),
                ('title', models.ForeignKey(help_text='Title authored by this author', on_delete=django.db.models.deletion.CASCADE, related_name='author_relationships', to='titles.title')),
            ],
            options={
                'verbose_name': 'Author-Title Relationship',
                'verbose_name_plural': 'Author-Title Relationships',
                'ordering': ['role', 'author__last_name'],
            },
        ),
        migrations.AddField(
            model_name='title',
            name='authors',
            field=models.ManyToManyField(help_text='Authors of the work', related_name='titles', through='titles.AuthorTitle', to='authors.author'),
        ),
        migrations.AddIndex(
            model_name='authortitle',
            index=models.Index(fields=['role'], name='titles_auth_role_ee94cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='authortitle',
            unique_together={('author', 'title', 'role')},
        ),
    ]
