# Generated by Django 5.1.4 on 2024-12-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0019_authortitle_title_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesTransliteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transliterated_text', models.TextField(help_text='Romanized version of the series name', verbose_name='Romanized Text')),
                ('series', models.ForeignKey(help_text='The original series this transliteration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transliterations', to='titles.series', verbose_name='Series')),
            ],
            options={
                'verbose_name': 'Series Transliteration',
                'verbose_name_plural': 'Series Transliterations',
                'ordering': ['transliterated_text'],
            },
        ),
    ]
