# Generated by Django 5.1.4 on 2024-12-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0020_seriestransliteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='popularity_score',
            field=models.PositiveIntegerField(default=0, help_text='Calculated popularity score'),
        ),
        migrations.AlterField(
            model_name='title',
            name='isfdb_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ISFDB ID', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of page views'),
        ),
        migrations.AlterField(
            model_name='titletransliteration',
            name='transliterated_text',
            field=models.TextField(blank=True, help_text='Romanized version of the original text', null=True, verbose_name='Romanized Text'),
        ),
    ]
